# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               'Atoms of Confusion'
tagline:             'Understanding Misunderstanding'
description:         'Studying the fundamental elements of source code comprehension from the ground up.'
url:                 http://atomsofconfusion.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dan Gopstein
#  url:               https://twitter.com/mdo
  email:             dgopstein@nyu.edu

# Custom vars
#version:             1.0.0
